version: "3"

services:
  postgres:
    container_name: go-user-api
    image: postgres
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
