// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://gabrielhijazi.dev/terms",
        "contact": {
            "name": "Gabriel Hijazi",
            "url": "http://support.hitechline.dev",
            "email": "hijazi.root@gmail.com"
        },
        "license": {
            "name": "Copyright (c) Gabriel Hijazi Fraga Santos",
            "url": "http://gabrielhijazi.dev"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Users API - GoLang",
	Description:      "Complete user API with PostgreSQL database and Kafka for event streaming",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
